import * as dotenv from 'dotenv';
import { Dialect } from 'sequelize/types';

dotenv.config({ path: './.env' });

export const config = {
  development: {
    db_host: process.env.DB_HOSTNAME,
    secret: process.env.JWT_SECRET,
    db_name: process.env.DB_NAME,
    db_user: process.env.DB_USERNAME,
    db_password: process.env.DB_PASSWORD,
    db_driver: process.env.DB_DRIVER as Dialect,
    db_port: process.env.DB_PORT,
    port: process.env.PORT,
    smtp_email: process.env.SMTP_EMAIL,
    smtp_email_password: process.env.SMTP_EMAIL_PASSWORD,
    smtp_host: process.env.SMTP_HOST,
    smtp_port: process.env.SMTP_PORT,
    smtp_service: process.env.SMTP_SERVICE,
    smtp_secure: process.env.SMTP_SECURE,
    admin_email: process.env.ADMIN_EMAIL,
    local_test_mail: process.env.LOCAL_TEST_MAIL,
    is_send_email: process.env.IS_SEND_EMAIL,
    is_aws_mail_service_used: process.env.IS_AWS_MAIL_SERVICE_USED,
    aws_smtp_host: process.env.AWS_SMTP_HOST,
    aws_smtp_user: process.env.AWS_SMTP_USER,
    aws_smtp_password: process.env.AWS_SMTP_PASSWORD,
    aws_from_mail: process.env.AWS_FROM_MAIL,
    aws_smtp_port: process.env.AWS_SMTP_PORT,
    aws_smtp_secure: process.env.AWS_SMTP_SECURE
  },
  test: {
    db_host: process.env.DB_HOSTNAME,
    secret: process.env.JWT_SECRET,
    db_name: process.env.DB_NAME,
    db_user: process.env.DB_USERNAME,
    db_password: process.env.DB_PASSWORD,
    db_driver: process.env.DB_DRIVER as Dialect,
    db_port: process.env.DB_PORT,
    port: process.env.PORT,
    smtp_email: process.env.SMTP_EMAIL,
    smtp_email_password: process.env.SMTP_EMAIL_PASSWORD,
    smtp_host: process.env.SMTP_HOST,
    smtp_port: process.env.SMTP_PORT,
    smtp_service: process.env.SMTP_SERVICE,
    smtp_secure: process.env.SMTP_SECURE,
    admin_email: process.env.ADMIN_EMAIL,
    local_test_mail: process.env.LOCAL_TEST_MAIL,
    is_send_email: process.env.IS_SEND_EMAIL,
    is_aws_mail_service_used: process.env.IS_AWS_MAIL_SERVICE_USED,
    aws_smtp_host: process.env.AWS_SMTP_HOST,
    aws_smtp_user: process.env.AWS_SMTP_USER,
    aws_smtp_password: process.env.AWS_SMTP_PASSWORD,
    aws_from_mail: process.env.AWS_FROM_MAIL,
    aws_smtp_port: process.env.AWS_SMTP_PORT,
    aws_smtp_secure: process.env.AWS_SMTP_SECURE
  },
  production: {
    db_host: process.env.DB_HOSTNAME,
    secret: process.env.JWT_SECRET,
    db_name: process.env.DB_NAME,
    db_user: process.env.DB_USERNAME,
    db_password: process.env.DB_PASSWORD,
    db_driver: process.env.DB_DRIVER as Dialect,
    db_port: process.env.DB_PORT,
    port: process.env.PORT,
    smtp_email: process.env.SMTP_EMAIL,
    smtp_email_password: process.env.SMTP_EMAIL_PASSWORD,
    smtp_host: process.env.SMTP_HOST,
    smtp_port: process.env.SMTP_PORT,
    smtp_service: process.env.SMTP_SERVICE,
    smtp_secure: process.env.SMTP_SECURE,
    admin_email: process.env.ADMIN_EMAIL,
    local_test_mail: process.env.LOCAL_TEST_MAIL,
    is_send_email: process.env.IS_SEND_EMAIL,
    is_aws_mail_service_used: process.env.IS_AWS_MAIL_SERVICE_USED,
    aws_smtp_host: process.env.AWS_SMTP_HOST,
    aws_smtp_user: process.env.AWS_SMTP_USER,
    aws_smtp_password: process.env.AWS_SMTP_PASSWORD,
    aws_from_mail: process.env.AWS_FROM_MAIL,
    aws_smtp_port: process.env.AWS_SMTP_PORT,
    aws_smtp_secure: process.env.AWS_SMTP_SECURE
  }
};
